import "./globals.css";
import { Inter } from "next/font/google";
import StyledJsxRegistry from "@/settings/StyleRegistry";
import Navegacion from "@/components/navegacion/Navegacion";
import { ColorAleatorioProvider } from "@/context/ColorAleatorio";
import { UsuarioVistaPreviaProvider } from "@/context/UsuarioVistaPrevia";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sense",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StyledJsxRegistry>
          <UsuarioVistaPreviaProvider>
            <ColorAleatorioProvider>
            <Navegacion/>
            {children}</ColorAleatorioProvider>
          </UsuarioVistaPreviaProvider>
        </StyledJsxRegistry>
      </body>
    </html>
  );
}
